export const categories=[
	['Awards & Trophies','Thoughtfully crafted recognition pieces for milestones, teams and achievements.','RECOGNITION','/products/academic-excellence-trophy.jpg'],
	['Temple Replicas','Detailed laser-cut replicas that bring devotion, heritage and architecture into your space.','DEVOTION','/products/golden-temple-replica.jpg'],
	['Art & Decor','Statement pieces and cultural artworks made to add character to meaningful spaces.','EXPRESSION','/products/warrior-statue.jpg'],
	['Personalized Gifts','Useful and memorable wooden creations made personal for the people and moments that matter.','THOUGHTFUL GIFTING','/products/wooden-inlay-box.jpg']
]

export const products=[
	['Academic Excellence Trophy','Awards & Trophies','A distinctive recognition piece for academic milestones and outstanding achievement.','/products/academic-excellence-trophy.jpg'],
	['Acharya Divas Award','Awards & Trophies','A thoughtful award created to honour teachers, mentors and lifelong guidance.','/products/acharya-divas-clean.jpg'],
	['Ahilyabai Holkar Award','Awards & Trophies','A meaningful recognition piece inspired by the legacy of courage, leadership and service.','/products/ahilyabai holkar award.jpg'],
	['Lokmata Ahilyabai Holkar Award','Awards & Trophies','A distinguished recognition piece honouring Lokmata Ahilyabai Holkar and her legacy of leadership and service.','/products/lokmata ahilyabai holkar 3D award.jpg'],
	['Honorary Memento Award','Awards & Trophies','A distinguished memento for honouring meaningful contribution, service and achievement.','/products/honorary memento award.jpg'],
	['Shrinathji Religious Award','Awards & Trophies','A devotional recognition piece inspired by Shrinathji, created for meaningful honouring and display.','/products/shrinathji religious award.jpg'],
	['Excellent Performer Award','Awards & Trophies','A polished award for celebrating consistent performance and exceptional contribution.','/products/excellent-performer-award.jpg'],
	['MIPL Trophy','Awards & Trophies','A customisable trophy designed for team achievements and memorable victories.','/products/mipl-trophy.jpg'],
	['MSME Day Award','Awards & Trophies','A commemorative award for celebrating enterprise, growth and contribution.','/products/msme-day-award.jpg'],
	['Play Class Award','Awards & Trophies','A cheerful recognition piece for young achievers and classroom milestones.','/products/play-class-award.jpg'],
	['Grandparents Day Award','Awards & Trophies','A heartfelt recognition piece for celebrating grandparents and the memories they create.','/products/grandparents day award.jpg'],
	['Indian Red Cross Society Award','Awards & Trophies','A distinguished recognition piece for honouring humanitarian service and community contribution.','/products/indian red cross society award.jpg'],
	['Rotary Appreciation Award','Awards & Trophies','A warm appreciation award for service, collaboration and community impact.','/products/rotary-appreciation-award.jpg'],
	['Star Performer Trophy','Awards & Trophies','A bold trophy for recognising standout effort and performance.','/products/star-performer-trophy.jpg'],
	['Golden Temple Replica','Temple Replicas','A detailed wooden interpretation of the Golden Temple for devotional display.','/products/golden-temple-replica.jpg'],
	['Hastinapur Memento','Temple Replicas','A crafted memento inspired by the heritage and spiritual history of Hastinapur.','/products/hastinapur-memento.jpg'],
	['Hastinapur Jain Temple','Temple Replicas','A detailed devotional replica celebrating the Jain heritage and sacred architecture of Hastinapur.','/hastinapur jain temple.jpg'],
	['Mahaveer Jain Temple','Temple Replicas','A finely detailed temple replica made for reflective and devotional spaces.','/products/mahaveer-jain-temple.jpg'],
	['Shri Mahavir Ji Digambar Jain Temple','Temple Replicas','A detailed devotional temple replica celebrating Shri Mahavir Ji and Digambar Jain heritage.','/shri mahavir ji digambar jain temple (2).jpg'],
	['Gurudwara Sri Hemkund Sahib','Temple Replicas','A detailed devotional replica celebrating the sacred architecture and spiritual heritage of Sri Hemkund Sahib.','/gurdwara sri hemkund sahib.jpg'],
	['Ram Mandir Replica','Temple Replicas','A meaningful architectural replica crafted for display and gifting.','/products/ram-mandir-replica.jpg'],
	['Shri Ram Mandir Ayodhya','Temple Replicas','A detailed devotional replica celebrating the sacred Ram Mandir in Ayodhya.','/shri ram mandir ayodhya (2).jpg'],
	['Warrior Statue','Art & Decor','A striking handcrafted statue that brings strength and character to a room.','/products/warrior-statue.jpg'],
	['Indian Freedom Fighters Cutout','Art & Decor','A meaningful cultural cutout celebrating the courage and legacy of India\'s freedom fighters.','/indian freedom fighters cutout.jpg'],
	['Lion Cutout','Art & Decor','A bold decorative cutout that brings strength and character to a meaningful space.','/lion cutout.jpg'],
	['Doraemon and Nobita Cutouts','Art & Decor','A playful decorative cutout set that brings familiar characters and personality to a creative space.','/doraemon nobita cutouts.jpg'],
	['Guru Nanak Dev Ji Wall Art','Art & Decor','A meaningful wall art piece celebrating the spiritual legacy and teachings of Guru Nanak Dev Ji.','/guru nanak dev ji wall art.jpg'],
	['Wooden Candle Holder Decor','Art & Decor','A warm wooden decor piece designed to bring character and ambient light to a meaningful space.','/wooden candle holder decor.jpg'],
	['Carved Wooden Floral Wall Art','Art & Decor','A handcrafted floral wall art piece that adds warmth, texture and natural character to a space.','/carved wooden floral wall art.jpg'],
	['Flower Wooden Wall Art','Art & Decor','A handcrafted floral wooden wall art piece that adds warmth and natural character to a space.','/flower wooden wall art.jpg'],
	['Flower Jaali Wooden Wall Art','Art & Decor','A detailed floral jaali wall art piece combining traditional pattern work with handcrafted wooden texture.','/flower jaali wooden wall art(2).jpg'],
	['Square Jaali Wooden Wall Art','Art & Decor','A detailed geometric wooden wall art piece that adds texture and crafted character to a space.','/square jaali wooden wall art.jpg'],
	['Wooden Jaali Wall Art','Art & Decor','A detailed handcrafted jaali wall art piece that adds texture and traditional character to a space.','/wooden jaali wall art (2).jpg'],
	['Shri Krishna Flute Wooden Wall Art','Art & Decor','A devotional wooden wall art piece celebrating Shri Krishna and the music of his flute.','/shri krishna flute wooden wall art.jpg'],
	['Shri Krishna Wooden Wall Art','Art & Decor','A devotional wooden wall art piece celebrating Shri Krishna and bringing a serene presence to a space.','/shri krishna wooden wall art.jpg'],
	['Shri Baal Krishna Cutout','Art & Decor','A playful devotional cutout celebrating Baal Krishna and adding character to a meaningful space.','/shri baal krishna  cutout.jpg'],
	['Shri Ganesha Wooden Wall Art','Art & Decor','A devotional wooden wall art piece celebrating Shri Ganesha and bringing an auspicious presence to a space.','/shri ganesha wooden wall art.jpg'],
	['Hand Candle Holder Wooden Wall Art','Art & Decor','A warm handcrafted wall art piece that combines sculptural detail with candlelight.','/hand candle holder wooden wall art.jpg'],
	['Circular Wooden Wall Art','Art & Decor','A handcrafted circular wooden wall art piece that adds texture and character to a meaningful space.','/circular wooden wall art (2).jpg'],
	['Circular Peacock Wooden Wall Art','Art & Decor','A detailed circular wall art piece featuring a peacock motif and crafted wooden texture.','/circular peacock wooden wall art.jpg'],
	['Shri Ram Wooden Wall Art','Art & Decor','A devotional wooden wall art piece celebrating Shri Ram and bringing a meaningful presence to a space.','/shri ram wooden wall art.jpg'],
	['Shri Gautam Buddha Wooden Wall Art','Art & Decor','A serene devotional wooden wall art piece inspired by the teachings and presence of Gautam Buddha.','/shri gautam buddha wooden wall art.jpg'],
	['Shubh Laabh Wooden Wall Art','Art & Decor','An auspicious wooden wall art piece designed to bring traditional warmth and positive character to a space.','/shubh laabh wooden wall art.jpg'],
	['Aatithi Plaque','Personalized Gifts','A welcoming plaque designed to make a home, studio or gathering space feel personal.','/products/aatithi-plaque.jpg'],
	['Elephant Jigsaw Puzzle','Personalized Gifts','A thoughtful wooden puzzle that makes a playful and memorable gift for all ages.','/elephant jigsaw puzzle.jpg'],
	['Butterfly Jigsaw Puzzle','Personalized Gifts','A colourful wooden puzzle that makes a playful and memorable gift for all ages.','/butterfly jigsaw puzzle.jpg'],
	['Snake Jigsaw Puzzle','Personalized Gifts','A playful wooden puzzle that makes a memorable gift for curious minds of all ages.','/snake jigsaw puzzle (1).jpg'],
	['Snake Jigsaw Puzzle 2','Personalized Gifts','A second playful wooden snake puzzle design that makes a memorable gift for curious minds of all ages.','/snake jigsaw puzzle 2.jpg'],
	['Dinosaur Jigsaw Puzzle','Personalized Gifts','A playful wooden dinosaur puzzle that makes a memorable gift for curious minds of all ages.','/dinosaur jigsaw puzzle.jpg'],
	['Berries Wooden Puzzle','Personalized Gifts','A colourful wooden puzzle that makes a playful and memorable gift for curious minds of all ages.','/berries wooden puzzle.jpg'],
	['Animals Wooden Puzzle','Personalized Gifts','A playful wooden animals puzzle that makes a memorable gift for curious minds of all ages.','/animals wooden puzzle.jpg'],
	['Wooden Inlay Box','Personalized Gifts','A practical keepsake box with a crafted inlay finish for thoughtful gifting.','/products/wooden-inlay-box.jpg']
]

export function slugify(value){
	return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
}

